server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:          #表示该配置直接为Spring容器负责处理
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #配置当前要使用的数据源的操作类型那个
    driver-class-name: com.mysql.jdbc.Driver       #配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/hugui?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: hugui
    password: 123456
#    filters: stat,wall,log4j     #druid监控配置
    dbcp2:
      min-idle: 5         #数据库连接池的最小维持连接数
      initial-size: 5     #初始化提供的连接数
      max-total: 5          #最大的连接数
      max-wait-millis: 200        #等待连接获取的最大超时时间
swagger2:
  enable: true


